// Module imports
import { Component } from "@angular/core";
import { MatIconModule } from "@angular/material/icon";
import { AsyncPipe } from "@angular/common";
import { ActivatedRoute, RouterModule } from "@angular/router";
import { CoreService, DataLangPipe, LangPipe, LangRouter } from "ngx-ute-core";

// Project imports
import { SiteHeader } from "@shared/site/header/header";
import { SiteFooter } from "@shared/site/footer/footer";

@Component({
    selector: "app-about",
    standalone: true,
    imports: [SiteHeader, SiteFooter, MatIconModule, AsyncPipe, LangPipe, DataLangPipe, RouterModule, LangRouter],
    templateUrl: "./about.html",
    styleUrl: "./about.scss",
})
export class AboutPage {
    public page: any = {};

    /**
     * Constructor of the AboutPage class.
     * Initializes the component with the about page data.
     * The page data is loaded from the route resolver.
     * The pages data is loaded from the assets/data/pages.json file.
     * The about page is generated by mapping the pages data to the page property.
     *
     * @param coreService The core service, used to get the language and other useful informations.
     * @param activatedRoute The activated route, used to get the data from the route resolver.
     */
    constructor(public readonly coreService: CoreService, private activatedRoute: ActivatedRoute) {
        const resolve = this.activatedRoute.snapshot.data["data"];
        const { pages } = resolve.data;

        this.page = pages.about;
    }
}
